"""全面测试脚本"""
import rsnum as np
import math

errors = []

def check(name, condition, detail=""):
    if condition:
        print(f"  ✓ {name}")
    else:
        print(f"  ✗ {name} - {detail}")
        errors.append(name)


print("=== 1. 基础属性测试 ===")
a = np.array([[1, 2, 3], [4, 5, 6]])
check("shape", a.shape == (2, 3), str(a.shape))
check("ndim", a.ndim == 2)
check("size", a.size == 6)
check("dtype", a.dtype == "float64")

print("\n=== 2. 构造函数测试 ===")
z = np.zeros((2, 3))
check("zeros shape", z.shape == (2, 3))
o = np.ones((2, 3))
check("ones shape", o.shape == (2, 3))
e = np.eye(3)
check("eye 3x3", e.shape == (3, 3))
e4 = np.eye(3, 4)
check("eye 3x4", e4.shape == (3, 4))
arr = np.arange(5)
check("arange(5)", arr.tolist() == [0, 1, 2, 3, 4])
arr2 = np.arange(2, 5)
check("arange(2,5)", arr2.tolist() == [2, 3, 4])
ls = np.linspace(0, 1, 5)
check("linspace(0,1,5)", ls.tolist() == [0.0, 0.25, 0.5, 0.75, 1.0])
f = np.full((2, 3), 7.0)
check("full", f.tolist() == [[7.0, 7.0, 7.0], [7.0, 7.0, 7.0]])
emp = np.empty((2, 2))
check("empty shape", emp.shape == (2, 2))
check("identity", np.identity(3).shape == (3, 3))
check("zeros_like", np.zeros_like(a).shape == a.shape)
check("ones_like", np.ones_like(a).shape == a.shape)
check("full_like", np.full_like(a, 5).shape == a.shape)

print("\n=== 3. 对象方法测试 ===")
a2 = np.array([[1, 2, 3], [4, 5, 6]])
check("T", a2.T.shape == (3, 2))
check("reshape", a2.reshape(3, 2).shape == (3, 2))
check("flatten", a2.flatten().tolist() == [1, 2, 3, 4, 5, 6])
check("ravel", a2.ravel().tolist() == [1, 2, 3, 4, 5, 6])
check("sum", a2.sum() == 21.0)
check("mean", a2.mean() == 3.5)
check("min", a2.min() == 1.0)
check("max", a2.max() == 6.0)
check("copy", a2.copy().tolist() == a2.tolist())
check("argmax", np.argmax(a2) == 5)
check("argmin", np.argmin(a2) == 0)
a3 = np.array([3, 1, 2])
check("sort", np.sort(a3).tolist() == [1.0, 2.0, 3.0])
check("argsort", np.argsort(a3).tolist() == [1.0, 2.0, 0.0])
a4 = np.array([1, 2, 3, 4, 5])
check("nonzero", len(np.nonzero(a4)) == 1 and len(np.nonzero(a4)[0]) == 5)

print("\n=== 4. 数组操作测试 ===")
a3 = np.array([1, 2, 3])
a4 = np.array([4, 5, 6])
c = np.concatenate([a3, a4], axis=0)
check("concatenate", c.tolist() == [1, 2, 3, 4, 5, 6])
s = np.stack([a3, a4], axis=0)
check("stack", s.shape == (2, 3))
check("hstack", np.hstack([a3, a4]).tolist() == [1, 2, 3, 4, 5, 6])
v = np.vstack([a3, a4])
check("vstack", v.shape == (2, 3))
check("expand_dims", np.expand_dims(a3, 0).shape == (1, 3))
check("squeeze", np.squeeze(np.array([[1]])).tolist() == 1.0)

print("\n=== 5. 数学函数测试 ===")
check("sin(0)", np.sin([0]).tolist() == [0.0])
check("cos(0)", np.cos([0]).tolist() == [1.0])
check("sqrt(4)", np.sqrt([4]).tolist() == [2.0])
check("exp(0)", np.exp([0]).tolist() == [1.0])
check("log(1)", np.log([1]).tolist() == [0.0])
check("abs(-5)", np.abs([-5]).tolist() == [5.0])
check("floor(1.5)", np.floor([1.5]).tolist() == [1.0])
check("ceil(1.5)", np.ceil([1.5]).tolist() == [2.0])
check("round(1.5)", np.around([1.5], 0).tolist() == [2.0])
check("sign(5)", np.sign([5]).tolist() == [1.0])
check("sign(-5)", np.sign([-5]).tolist() == [-1.0])
check("sign(0)", np.sign([0]).tolist() == [0.0])

print("\n=== 6. 统计函数测试 ===")
a5 = np.array([1, 2, 3, 4, 5])
check("sum", np.sum(a5).tolist() == 15.0)
check("mean", np.mean(a5).tolist() == 3.0)
check("median", np.median(a5).tolist() == 3.0)
check("min", np.min(a5).tolist() == 1.0)
check("max", np.max(a5).tolist() == 5.0)
check("ptp", np.ptp(a5).tolist() == 4.0)
check("std", abs(np.std(a5).tolist() - math.sqrt(2.0)) < 1e-10)
check("var", abs(np.var(a5).tolist() - 2.0) < 1e-10)
check("percentile(50)", np.percentile(a5, 50).tolist() == 3.0)

print("\n=== 7. 索引函数测试 ===")
cond = np.array([True, False, True])
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
result = np.where(cond, x, y)
check("where 3-elem", result.tolist() == [1, 20, 3])
check("select", np.select([np.array([True, False])], [np.array([1, 2])], 0).tolist() == [1, 0])

print("\n=== 8. ufunc测试 ===")
a6 = np.array([1, 2, 3])
b6 = np.array([4, 5, 6])
check("add", np.add(a6, b6).tolist() == [5, 7, 9])
check("subtract", np.subtract(a6, b6).tolist() == [-3, -3, -3])
check("multiply", np.multiply(a6, b6).tolist() == [4, 10, 18])
check("divide", np.divide(a6, b6).tolist() == [0.25, 0.4, 0.5])
check("power", np.power(a6, 2).tolist() == [1, 4, 9])
check("greater", np.greater(a6, 2).tolist() == [0, 0, 1])
check("less", np.less(a6, 2).tolist() == [1, 0, 0])
check("equal", np.equal(a6, 2).tolist() == [0, 1, 0])
check("logical_and", np.logical_and(np.array([1,0]), np.array([1,1])).tolist() == [1, 0])
check("logical_or", np.logical_or(np.array([1,0]), np.array([0,0])).tolist() == [1, 0])

print("\n=== 9. FFT测试 ===")
fft_data = np.fft([1.0, 2.0, 1.0, 0.0])
check("fft exists", len(fft_data) > 0)
ifft_data = np.ifft(fft_data)
check("ifft", len(ifft_data) > 0)
rfft_data = np.rfft([1.0, 2.0, 1.0, 0.0])
check("rfft", len(rfft_data) > 0)

print("\n=== 10. linalg测试 ===")
m = np.array([[1.0, 2.0], [3.0, 4.0]])
check("det", abs(np.linalg.det(m) + 2.0) < 1e-10)
check("inv", np.linalg.inv(m).shape == (2, 2))
check("dot", np.linalg.dot(a6, b6) == 32.0)
check("matmul", np.linalg.matmul(m, m).shape == (2, 2))

print("\n=== 11. 常量测试 ===")
check("pi", np.pi == math.pi)
check("e", np.e == math.e)
check("inf", np.inf == float('inf'))
check("nan", math.isnan(np.nan))

print("\n=== 12. 判断函数测试 ===")
check("isnan(0)", np.isnan([0]).tolist() == [0.0])
check("isinf(inf)", np.isinf([float('inf')]).tolist() == [1.0])
check("isfinite(1)", np.isfinite([1]).tolist() == [1.0])

print("\n=== 13. random测试 ===")
r = np.random.rand(3)
check("rand shape", len(r) == 3)
rn = np.random.randn(3)
check("randn shape", len(rn) == 3)

if errors:
    print(f"\n❌ 失败: {len(errors)} 个测试失败:")
    for e in errors:
        print(f"  - {e}")
else:
    print("\n✅ 所有测试通过!")